backend:
  name: github
  repo: 000alen/without-mask-society
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: landing
    label: Landing
    folder: landing
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, widget: hidden, default: "landing" }

      # Nav
      - { name: twitter_url, label: "Twitter url" }
      - { name: instagram_url, label: "Instagram url" }
      - { name: discord_url, label: "Discord url" }
      - { name: opensea_url, label: "Opensea url" }
      - { name: digitalrocket_url, label: "DigitalRocket url" }

      # Hero
      - { name: hero_title, label: "Hero - Title", widget: text }
      - {
          name: hero_buttons,
          label: "Hero - Buttons",
          widget: list,
          fields:
            [
              { name: hero_button_text, label: "Hero - Button text" },
              {
                name: hero_button_color,
                label: "Hero - Button color",
                widget: color,
              },
              {
                name: hero_button_icon,
                label: "Hero - Button icon",
                widget: select,
                options: [opensea, discord, none],
              },
              { name: hero_button_url, label: "Hero - Button url" },
            ],
        }
      - {
          name: hero_showcase,
          label: "Hero - Showcase",
          widget: list,
          fields:
            [
              {
                name: hero_showcase_unmasked,
                label: "Hero - Showcase unmasked",
                widget: image,
              },
              {
                name: hero_showcase_masked,
                label: "Hero - Showcase masked",
                widget: image,
              },
              { name: hero_showcase_url, label: "Hero - Url" },
            ],
        }

      # About
      - { name: about_title, label: "About - Title" }
      - { name: about_text, label: "About - Text", widget: text }

      # City
      - { name: city_title, label: "City - Title" }
      - { name: city_text, label: "City - Text", widget: text }
      - {
          name: city_members,
          label: "City - Members",
          widget: list,
          fields:
            [
              { name: city_member_name, label: "City - Member name" },
              {
                name: city_member_description,
                label: "City - Member description",
              },
              {
                name: city_member_avatar,
                label: "City - Member avatar",
                widget: image,
              },
              {
                name: city_member_socials,
                label: "City - Member socials",
                widget: list,
                fields:
                  [
                    {
                      name: city_member_social_name,
                      label: "City - Social name",
                      widget: select,
                      options: [twitter, linkedin],
                    },
                    {
                      name: city_member_social_url,
                      label: "City - Social url",
                    },
                  ],
              },
            ],
        }

      # Forest
      - { name: forest_title, label: "Forest - Title" }
      - { name: forest_text, label: "City - Text", widget: text }
      - {
          name: forest_milestones,
          label: "Forest - Milestones",
          widget: list,
          fields:
            [
              {
                name: forest_milestone_percent,
                label: "Forest - Milestone Percent",
                widget: text,
              },
              {
                name: forest_milestone_text,
                label: "Forest - Milestone text",
                widget: text,
              },
            ],
        }
      - {
          name: forest_showcase,
          label: "Forest - Showcase",
          widget: list,
          fields:
            [
              {
                name: forest_showcase_image,
                label: "Forest - Showcase image",
                widget: image,
              },
              { name: forest_showcase_url, label: "Forest - Showcase url" },
            ],
        }

      # Planets
      - { name: planets_title, label: "Planet - Title" }
      - { name: planets_text, label: "Planet - Text", widget: text }

      # Pool
      - { name: pool_title, label: "Pool - Title" }
      - { name: pool_text, label: "Pool - Text", widget: text }

      # FAQ
      - { name: faq_title, label: "FAQ - Title" }
      - name: faq_questions
        label: "FAQ - Questions"
        widget: list
        fields:
          - { name: faq_question, label: "FAQ - Question" }
          - { name: faq_answer, label: "FAQ - Answer", widget: text }

      # Mailing
      - { name: mailing_text, label: "Mailing - Text" }

  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
